const mongoose = require('mongoose');

const documentSchema = new mongoose.Schema({
  iddocumentocontable: { type: String },
  idcentro_costos: { type: String },
  idtipo_documento: { type: String },
  idestado: { type: String },
  idestadosunat: { type: String },
  idmoneda: { type: String },
  idcondicion_pago: { type: String },
  id_serie: { type: String },
  idempresa: { type: String },
  tipo_operacion: { type: String },
  numero_documento: { type: String },
  id_origen: { type: String },
  direccion: { type: String },
  codigo_pedido: { type: String },
  serie_pedido: { type: String },
  id_modulo: { type: String },
  identidad_emisor: { type: String },
  identidad_receptora: { type: String },
  monto_subtotal: { type: String },
  monto_igv: { type: String },
  monto_total: { type: String },
  monto_total_desc: { type: String },
  valorigv: { type: String },
  fecha_emision: { type: String },
  fecha_anulacion: { type: String },
  fecha_vencimiento: { type: String },
  otros_tributos: { type: String },
  otros_cargos: { type: String },
  observacion: { type: String },
  log_usuariocreacion: { type: String },
  log_fechacreacion: { type: String },
  log_usuariomodif: { type: String },
  log_fechamodif: { type: String },
  log_estado: { type: String },
  monto_isc: { type: String },
  serie_compras: { type: String },
  total_precio_venta: { type: String },
  peso_bruto: { type: String },
  peso_neto: { type: String },
  monto_igv_gratuito: { type: String },
  codigoordencompra: { type: String },
});
const documento = mongoose.model("documentos", documentSchema);
module.exports = documento;
